[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 } # Un peu d'air autour du texte
opacity = 0.95               # Voir le sujet PDF en transparence !
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
blur = true
title = ""

[scrolling]
history = 10000              # Garder beaucoup d'historique (utile pour les logs valgrind)

[font]
# Assurez-vous d'avoir une Nerd Font install√©e (ex: Hack ou JetBrainsMono)
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.0

[colors]
[colors.primary]
background = "#202020"
foreground = "#f8f8f2"